name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
             fetch-depth: 0
      - uses: actions/setup-python@v3  
        with:
            python-version: 3.11
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-simplepdf
      - name: Build and Commit
        uses: iSOLveIT/sphinx-pdf-generate-action@main
        with:
          config_file_path: doc/conf.py
          target_branch: 'gh-pages'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: site
